leftnav:
- identifier: bbc7600c-0de3-4980-8e78-2e537ddd687e
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: df733917-1aa0-4cda-96e8-dd68213c1daa
  name: Calendar
  pageRef: /pages/calendar
  weight: 20
- identifier: 821272d4-fda7-47cc-bbfc-b97940f2aa3d
  name: Instructor Insights
  pageRef: /pages/instructor-insights
  weight: 30
- identifier: e50d26dc-8dfc-4fc3-8a91-ba3695fc77b6
  name: Readings
  pageRef: /pages/readings
  weight: 40
- identifier: ed784e72-fee7-48d9-bcee-f40b88619fd9
  name: Class Summaries
  pageRef: /pages/class-summaries
  weight: 50
- identifier: def28f59-bf40-4be3-b34d-3343aaf9ffef
  name: Assignments
  pageRef: /pages/assignments
  weight: 60
- identifier: cb0f4dea-60b6-4c83-93a8-6c4d34389f5d
  name: Discussion Prompts
  pageRef: /pages/discussion-prompts
  parent: def28f59-bf40-4be3-b34d-3343aaf9ffef
  weight: 10
- identifier: 8d97e2c4-96fa-44ea-a0bf-2e0bb3d5490e
  name: Essays
  pageRef: /pages/assignment
  parent: def28f59-bf40-4be3-b34d-3343aaf9ffef
  weight: 20
- identifier: 1c1acc28-ea54-4c00-bc95-f31422e3c20a
  name: Report
  pageRef: /pages/report-guidelines
  parent: def28f59-bf40-4be3-b34d-3343aaf9ffef
  weight: 30
